---
- name: add official Docker CE Stable repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    enabled: yes

- name: ensure docker is installed
  yum:
    name: docker-ce-{{ docker_version }}
    state: present

- name: ensure python-docker-py is installed
  yum:
    name: python-docker-py
    state: latest

- name: ensure spotify/docker-gc is croned
  cron:
    name: 'spotify/docker-gc'
    weekday: 1
    hour: 2
    minute: 0
    job: 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc:ro spotify/docker-gc'

- name: setup docker storage driver - create directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: setup docker storage driver - create configuration
  template:
    src: storage-driver.conf.j2
    dest: /etc/systemd/system/docker.service.d/storage-driver.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart docker

- name: setup proxy for docker
  template:
    src: proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf
    owner: root
    group: root
    mode: 0644
  when: docker_http_proxy or docker_https_proxy or docker_no_proxy
  notify:
    - reload systemd
    - restart docker

- name: ensure 'docker' group present
  group:
    name: docker
    state: present
    system: yes

- name: add users into 'docker' group
  user:
    append: yes
    groups: docker
    state: present
    name: '{{ item }}'
  with_items: '{{ docker_users }}'

- name: ensure docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
